name: second-workflow
on: 
  push:
  pull_request:
    types: [opened]
    
jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install nose pylint
      - name: Pylint tests
        run: |
          python -m python pylint .
      - name: Nosetests
        run: |
          nosetests